language: python

python:
  - "pypy"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install --editable .

script: make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
